version: "3.8"

services:
  issuance-service:
    build: ./issuance-service
    container_name: issuance-service
    ports:
      - "3000:3000"

  verification-service:
    build: ./verification-service
    container_name: verification-service
    ports:
      - "3001:3001"
    depends_on:
      - issuance-service
    environment:
      - ISSUANCE_SERVICE_URL=http://issuance-service:3000
